import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  AppConfigSchema,
  ClubSchema,
  DiscountCouponSchema,
  DiscountUsageSchema,
  GemLogSchema,
  MemberSchema,
  MemberTagSchema,
  MenuCostSchema,
  MenuSchema,
  MissionCompleteSchema,
  MissionSchema,
  ProductCategorySchema,
  ProductSchema,
  PurchaseSchema,
  RegionSchema,
  ShopGroupSchema,
  OrderItemSchema,
  OrderReviewSchema,
  OrderSchema,
  OrderCustomerMessageSchema,
  ShopSchema,
  PrintActionSchema,
  ShopPrintViewSchema,
  ShopPrinterSchema,
  DeliveryAreaSchema,
  ShopUserSchema,
  PaymentGatewaySchema,
  PaymentTokenSchema,
  PaymentSchema,
  SmsAccountSchema,
  SmsSchema,
  SmsTemplateSchema,
  ThemeSchema,
  UserSchema,
  WalletLogSchema,
  WalletSchema,
} from './schemas';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      AppConfigSchema,
      ClubSchema,
      DiscountCouponSchema,
      DiscountUsageSchema,
      GemLogSchema,
      MemberTagSchema,
      MemberSchema,
      MenuCostSchema,
      MenuSchema,
      MissionCompleteSchema,
      MissionSchema,
      ProductCategorySchema,
      ProductSchema,
      PurchaseSchema,
      RegionSchema,
      ShopGroupSchema,
      OrderItemSchema,
      OrderReviewSchema,
      OrderSchema,
      OrderCustomerMessageSchema,
      ShopUserSchema,
      PaymentGatewaySchema,
      PaymentTokenSchema,
      PaymentSchema,
      ShopSchema,
      PrintActionSchema,
      ShopPrintViewSchema,
      ShopPrinterSchema,
      DeliveryAreaSchema,
      SmsAccountSchema,
      SmsTemplateSchema,
      SmsSchema,
      ThemeSchema,
      UserSchema,
      WalletLogSchema,
      WalletSchema,
    ]),
  ],
  exports: [TypeOrmModule],
})
export class SchemasModule {}
